version: '3'
services:
    sips_base:
        image: unity-sds/sounder_sips_base:r0.1.0
        hostname: local
        build:
            context: base/ 
            dockerfile: $PWD/base/Dockerfile
    spss_pge:
        image: unity-sds/sounder_sips_pge:r0.1.0
        hostname: local
        build:
            context: spss/
            dockerfile: $PWD/spss/Dockerfile
